### ISSUE TITLE
edit legally transfers

### ISSUE THREAD

**Issue by mbrochhausen** [d-acts/d-acts#14]
make changes similar to those mentioned in #13

**Comment by mbrochhausen** [comment]
I think we need to consider obsoleting this object property. Since SLGDCs will no longer exist, it isn't clear that is is still needed.
Comments?

**Comment by neilotte** [comment]
Agreed.

**Comment by mbrochhausen** [comment]
done: https://github.com/d-acts/d-acts/commit/0555a118018fdecab1074c069faf4485c3f86c66
