### ISSUE TITLE
Multiple Annotation Properties from Import Closure

### ISSUE THREAD

**Issue by CooperStansbury** [d-acts/d-acts#18]
This issue is in reference to an email thread between @mbrochhausen @neilotte. Primarily for tracking purposes.

`d-acts.owl` specifies 4 direct imports (BFO, pno, RO core, and IAO). These ontologies also import various combinations of themselves, with different versions.

See: 
1. `http://purl.obolibrary.org/obo/iao.owl/2015-02-23/iao.owl`
1. `http://purl.obolibrary.org/obo/bfo/classes-only.owl`

This results in duplicate annotation properties for classes with different import sources.  For example: BFO:entity has multiple rdfs:label properties from different places. This can be seen by hovering your mouse over the annotation property.

**Comment by mbrochhausen** [comment]
To the extent these were issues based on PNO and d-acts imports alone the following commit solved the problem:
https://github.com/d-acts/d-acts/commit/a565fb1c7f46f6ef621592c3c77cbfb1aca93daa

**Comment by CooperStansbury** [comment]
For reference, this issue is not new. Love the word 'autophagic.'

[#107](https://github.com/oborel/obo-relations/issues/107)

**Comment by mbrochhausen** [comment]
Thanks for the pointer
