### ISSUE TITLE
Missing RO Temporal Relations in D-acts

### ISSUE THREAD

**Issue by CooperStansbury** [d-acts/d-acts#19]
As we're revisiting the use of all the imports in D-acts. Note that we found that there are no temporal ordering relations in the imports. The file `ro-core.owl`, which is the version of RO used by D-acts, is missing the 'precedes' relation and its inverse, available in RO. 

ICO will definitely need this, and perhaps other, relations for ordering times.  

As communicated by @neilotte

**Comment by mbrochhausen** [comment]
We might need RO later, but at this point d-acts doesn't need those relations, hence I am going to close the issue.
Recommendation to import or MIREOT those entities into ICO.
