### ISSUE TITLE
'is about' and inverses

### ISSUE THREAD

**Issue by neilotte** [d-acts/d-acts#20]
In the file, I see that there are no inverses for 'is about' and its subrelations, except for the relation 'designates', for which I do see 'is designated by' hanging out, all by itself. However, 'designates', which appears to mean the same thing as 'denotes', is not a specified subrelation of 'is about'. 

Recommend obsoleting 'designates' and using 'denotes', and then finding or creating the inverses for 'is about' and its subrelations. 

Note: We need these in ICO, as we're adding 'prescribes' and 'is prescribed by' taken from the common core ontologies.

**Comment by mbrochhausen** [comment]
So, which file are you looking at? The development version or the release. In the development version 'designates' no longer exists and its inverse should probably be removed. Please also note that there is no inverse for 'is about' (at least to my knowledge).

**Comment by neilotte** [comment]
I see. I was looking in the wrong place. This will have to wait for the new release. It is odd that the RO would include inverses for its other relationships but not for 'is about' and its subs.
