### ISSUE TITLE
Label for 'Standing Declaration'

### ISSUE THREAD

**Issue by neilotte** [d-acts/d-acts#24]
I think 'standing declaration'--like many terms describing processes--is ambiguous between the process and the information content entity that is created by such a process. 

I would recommend reserving 'standing declaration' for the entity created, but 'directive information content entity' already seems to work here. 

This leaves the process. How about changing the label of this class to 'Act of Creating a Standing Declaration'? 

--Neil

**Comment by mbrochhausen** [comment]
I don't think that this is a really a problem or that the proposed solution is a good solution.

Look at deontic declaration: The outcome of what is now called "deontic declaration" is not a declaration or something we would call a declaration. Based on Reinach's theory the process is called declaration. That might not conform with the (fairly loosely enforced) rule within the OBO Foundry use -ing forms for processes, but that is just the name of the process.
So, I think the problem outlined doesn't exist, unless we plan that the outcome of a standing declaration be indeed a declaration (something which would run counter to Reinach's terminology entirely and which I wouldn't recommend).
Act of creating a standing declaration certainly rings wrong in my ears against Reinach's theory.

**Comment by neilotte** [comment]
I defer to you here Mathias.
