### ISSUE TITLE
Deontic Power Roles

### ISSUE THREAD

**Issue by neilotte** [d-acts/d-acts#25]
Thoughts about adding the following class? 

label "deontic power role"@en

definition "A deontic role that, if realized, is realized in the creation of a deontic role."@en

'editor note' "Rights and legal powers are deontic power roles. For instance, a consent power is a 
deontic power role that may be realized in the creation of a permission role, where the permission role then inheres in the person to whom consent has been provided."@en

**Comment by mbrochhausen** [comment]
+1
