### ISSUE TITLE
reversed definition for obligee role and obligor role?

### ISSUE THREAD

**Issue by sjbost** [d-acts/d-acts#27]
I think that the definitions for 'obligee role' and 'obligor role' need to be swapped. Currently 'obligee role' is the "receiver" and 'obligor role" is the "provider." But the Oxford English Dictionary, as well as a number of other sources and ontologies, define them oppositely. 

The Oxford English Dictionary defines the terms as follows:
Obligor, n. 1. Law. A person who is bound to another by contract, or who gives a bond to another; spec. a debtor.
Obligee, n. 1. Law. A person to whom another is bound by contract; one to whom a bond is given; spec. a creditor.

**Comment by mbrochhausen** [comment]
Sarah, can you please check whether that was done and if so, close the issue.

**Comment by mbrochhausen** [comment]
This issue was addressed by the following commits:
https://github.com/d-acts/d-acts/commit/0041b5cbddac6cc309cc6c1ff062364c6c86c456
https://github.com/d-acts/d-acts/commit/109d2207d3ca564ba74952cd1649ee071f936239
