### ISSUE TITLE
Organism (OBI_0100026) has no parent class

### ISSUE THREAD

**Issue by jonathanvajda** [d-acts/d-acts#28]
Organism appears to have been erroneously moved to be a sibling class of entity and 'Obsolete Class'.

Should have 'material entity' (BFO_0000040) as its immediate parent.

This error also impacts 'Homo sapiens', since it is a child class of 'organism'

**Comment by sjbost** [comment]
Hi Jonathan,

I'm unable to reproduce the problem and neither is my colleague here at UAMS. What file are you viewing and what tool are you using to view it?  Is PNO importing properly?

**Comment by jonathanvajda** [comment]
I am importing:
http://purl.obolibrary.org/obo/iao/d-acts.owl
<http://purl.obolibrary.org/obo/iao/d-acts.owl>

It points to release version 2019-01-30.

Which is
http://purl.obolibrary.org/obo/iao/d-acts/release/2019-01-30/d-acts.owl

If you search for the term 'organism' it doesn't have any subclass
statement. ('aggregate of organisms' does, however)

Should I be importing from a different source?

All the best,
Jonathan Vajda
/dʒɒnɑθɑn vaɪdɑ/

**Comment by sjbost** [comment]
Hmm. This is what I'm seeing. 
![d-acts](https://user-images.githubusercontent.com/13934641/53837894-5c9dde80-3f59-11e9-8cff-c303eb09755b.PNG)

**Comment by sjbost** [comment]
The reason I asked if you have PNO imported is because the subclass relationship is asserted in PNO (http://purl.obolibrary.org/obo/iao/pno/2019-02-21/pno.owl)

**Comment by sjbost** [comment]
Hi Jonathan,

I'm glad you got the problem fixed! 

Yes, PNO includes the assertion that 'organism' is a subclass of 'material entity.' When I open d-acts in Protege and go to 'organism,' I can hover my mouse over the subclass relationship and see "Asserted in: http://purl.obolibrary.org/obo/iao/pno/2019-02-21/pno.owl." Of course if PNO wasn't loaded into Protege, you wouldn't have been able to see that.

Best,
Sarah
