### ISSUE TITLE
RTR: social act

### ISSUE THREAD

**Issue by sjbost** [d-acts/d-acts#31]
Revise definition to remove "that needs to be perceived." 

In July 24, 2020 Moonshot Aims 2/4 meeting, Mathias stated that he believed he made a translation error of Rhinenacht's (sp?) work. Mathias will check the book in his office.

**Comment by sjbost** [comment]
@mbrochhausen Did you say that you made this change in the dev version of d-acts?

**Comment by mbrochhausen** [comment]
yes

**Comment by sjbost** [comment]
Then I will close this issue.

**Comment by mbrochhausen** [comment]
Yes, please *blush
