### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by hauschke** [d-acts/d-acts#36]
It would be beneficial for potential users of the d-acts ontology if this repo had a README explaining what it is about.

**Comment by mbrochhausen** [comment]
Absolutely! Thanks, we will be working on this and resolve the issue once we have it put up.

**Comment by mba-ufmg** [comment]
Hi, I have thought of providing a draft. I will send it today later. Can I?

Mauricio B. Almeida

**Comment by hauschke** [comment]
Thanks for taking action. While you are at that: The "About" section of this repo says "Automatically exported from code.google.com/p/d-acts", which could be more specific, too. :wink:

**Comment by mba-ufmg** [comment]
Hi, attached you will meet a Readme.md file with a suggestion. Some information is missing. There ara also a logo, if you want.
Let me know in case you would like to have a website for d-acts (it would be under my own site at UFMG or at NCOR-BR).
I couldn't find where to edit the "about" of the project.
Best
MBA

**Comment by mbrochhausen** [comment]
Hi Mauricio,

we cannot oppn the attachment. Can you please send that to me by email.

Best,
Mathias

**Comment by mba-ufmg** [comment]
Hi Mathias, I will send it now. It is a .md file, it can be opened with a simple editor, like Notepad (sorry in case you've already known this).

**Comment by CDowland** [comment]
Closing this because we added a ReadMe around September.
