### ISSUE TITLE
add owl:versionIRI 

### ISSUE THREAD

**Issue by sivaramarabandi** [d-acts/d-acts#9]
Currently only the latest version of d-acts can be linked to using 
   `http://purl.obolibrary.org/obo/iao/d-acts.owl` 
and the version it represents is provided in this tag:
   `<owl:versionInfo>release version 2017-02-20</owl:versionInfo>`

However there are times when a specific version needs to used/locked down in an application, and the only way to do it right now would be to save a local copy and linking to it in the catalog file. But this process is not robust, and can easily break. 

A better way is to link to the specific version of the ontology directly via the `owl:versionIRI`. It would be nice if a corresponding `owl:versionIRI` was also added to each release of d-acts. E.g.:
   `<owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/iao/2017-02-20/d-acts.owl"/>`

**Comment by utecht** [comment]
We do have releases tagged on github and a pattern match on our obolibrary purl.  So you can import any release version of d-acts.

e.g.
`http://purl.obolibrary.org/obo/iao/d-acts/release/2017-02-20/d-acts.owl`

However we are not using proper owl:versionIRIs but will add them to future releases.

Thank you for the suggestion.

**Comment by mbrochhausen** [comment]
From now on version IRIs are in place.
